version: '3'
services:
  zookeeper:
    image: zookeeper:3.5
    platform: linux/amd64
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    platform: linux/amd64
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  rabbitmq:
    image: rabbitmq:3.12.14-management
    ports:
      - "15673:15672"  # 将管理界面的端口映射到15673
      - "5673:5672"    # 将连接端口映射到5673