name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: ./.github/actions/setup-java
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean verify -DargLine="--add-opens java.base/java.lang=ALL-UNNAMED"

      - name: SonarQube Scan
        env:
          SONAR_HOST_URL: http://localhost:9000
          SONAR_LOGIN: ${{ secrets.SONAR_TOKEN }}
        run: mvn sonar:sonar \
          -Dsonar.projectKey=bilibili-integration \
          -Dsonar.host.url=$SONAR_HOST_URL \
          -Dsonar.login=$SONAR_LOGIN